# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/int_to_float/int_to_float.xci
# IP: The module: 'int_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/int_to_float/int_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_to_float'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/int_to_float/int_to_float.xci
# IP: The module: 'int_to_float' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/int_to_float/int_to_float_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'int_to_float'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
