# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/four_body_bram_sp/four_body_bram_sp.xci
# IP: The module: 'four_body_bram_sp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/four_body_bram_sp/four_body_bram_sp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_body_bram_sp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/four_body_bram_sp/four_body_bram_sp.xci
# IP: The module: 'four_body_bram_sp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/four_body_bram_sp/four_body_bram_sp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_body_bram_sp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
