# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/adder_suber/adder_suber.xci
# IP: The module: 'adder_suber' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/adder_suber/adder_suber_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_suber'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/adder_suber/adder_suber.xci
# IP: The module: 'adder_suber' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CodeFactory/RV-052B/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/adder_suber/adder_suber_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adder_suber'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
