# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/float_to_int/float_to_int.xci
# IP: The module: 'float_to_int' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/float_to_int/float_to_int_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_int'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: Z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/float_to_int/float_to_int.xci
# IP: The module: 'float_to_int' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/Documents/GitHub/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/float_to_int/float_to_int_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_to_int'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
