# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/310-w/Desktop/RV-052BG/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/DATA_Bram_1/DATA_Bram.xci
# IP: The module: 'DATA_Bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/310-w/Desktop/RV-052BG/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/DATA_Bram_1/DATA_Bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_Bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/310-w/Desktop/RV-052BG/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/DATA_Bram_1/DATA_Bram.xci
# IP: The module: 'DATA_Bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/310-w/Desktop/RV-052BG/RiscV-Pipeline-BranchPrediction-DynamicScheduling-CPU/cpu/cpu.srcs/sources_1/ip/DATA_Bram_1/DATA_Bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_Bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
